#!/usr/bin/env bash
# Keep a copy of Muse's minted API key where Tusker-run Muse can read it.
#
# Muse stores its account login in the macOS Keychain. Tusker's runner sandbox
# blocks the Keychain, so a Muse worker cannot authenticate. Muse also accepts
# META_API_KEY, which wins over the account login. This script copies the
# minted key out of the Keychain (as you, outside any sandbox) into a 0600 file,
# and installs a `muse` launcher that exports it before starting Muse.
#
#   muse-key.sh install    write the launcher and a launchd job, then sync
#   muse-key.sh sync       copy the current key from the Keychain
#   muse-key.sh check      sync, then probe the key; refresh it if rejected
#   muse-key.sh tick       sync every run, probe at most every PROBE_EVERY seconds
#   muse-key.sh uninstall  remove the launchd job, launcher and key file
#
# After install, set the Muse profile's command in ~/.config/tusker/config.yaml:
#   command: <launcher path printed by install> exec --json
set -euo pipefail

service="ai.meta.dev.credentials"
account="meta"
dir="${MUSE_KEY_DIR:-$HOME/.config/muse-tusker}"
key_file="$dir/api-key"
probe_stamp="$dir/last-probe"
launcher="${MUSE_KEY_LAUNCHER:-$HOME/.local/libexec/muse-tusker/muse}"
real_muse="${MUSE_REAL:-$HOME/.local/bin/muse}"
label="xyz.sarav.muse-key"
plist="$HOME/Library/LaunchAgents/$label.plist"
probe_every="${PROBE_EVERY:-21600}"
log() { printf '%s muse-key: %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >&2; }

notify() {
  log "$1"
  /usr/bin/osascript -e "display notification \"$1\" with title \"Muse key\"" >/dev/null 2>&1 || true
}

sync_key() {
  local secret key tmp
  if ! secret="$(/usr/bin/security find-generic-password -s "$service" -a "$account" -w 2>/dev/null)"; then
    notify "No Muse login in the Keychain. Run: muse login"
    return 1
  fi
  key="$(printf '%s' "$secret" | /usr/bin/plutil -extract api_key raw -o - - 2>/dev/null || true)"
  if [[ -z "$key" ]]; then
    notify "The Muse login has no minted API key. Run: muse login"
    return 1
  fi
  mkdir -p "$dir"
  chmod 700 "$dir"
  if [[ -r "$key_file" && "$(<"$key_file")" == "$key" ]]; then
    return 0
  fi
  tmp="$(mktemp "$dir/.api-key.XXXXXX")"
  printf '%s' "$key" >"$tmp"
  chmod 600 "$tmp"
  mv -f "$tmp" "$key_file"
  rm -f "$probe_stamp" # a new key gets probed on the next tick
  log "key updated"
}

# probe runs one tiny Muse turn. Status 0: accepted. 2: key rejected. 1: other failure.
probe() {
  local prompt out
  prompt="$(mktemp -t muse-key-probe)"
  printf 'Reply with the single word OK.\n' >"$prompt"
  out="$(cd "${TMPDIR:-/tmp}" && "$@" exec --prompt-file "$prompt" 2>&1)" && { rm -f "$prompt"; return 0; }
  rm -f "$prompt"
  if grep -qiE 'was rejected|unauthori[sz]ed|\b401\b|missing meta credentials' <<<"$out"; then
    return 2
  fi
  log "probe failed for another reason: $(tail -n 1 <<<"$out")"
  return 1
}

check() {
  sync_key
  local status=0
  probe "$launcher" || status=$?
  if [[ $status -eq 0 ]]; then
    date +%s >"$probe_stamp"
    return 0
  fi
  [[ $status -eq 2 ]] || return 1
  # Rejected: let Muse use its account login (not the env key) so it mints a
  # new key into the Keychain, then copy that.
  log "key rejected; asking Muse to refresh its login"
  probe env -u META_API_KEY "$real_muse" || true
  sync_key
  status=0
  probe "$launcher" || status=$?
  if [[ $status -eq 0 ]]; then
    date +%s >"$probe_stamp"
    log "key refreshed"
    return 0
  fi
  notify "Muse rejected its key after a refresh. Run: muse login"
  return 1
}

tick() {
  sync_key || return 1
  local last=0
  [[ -r "$probe_stamp" ]] && last="$(<"$probe_stamp")"
  if (($(date +%s) - last >= probe_every)); then
    check
  fi
}

install() {
  mkdir -p "$(dirname "$launcher")" "$HOME/Library/LaunchAgents" "$dir"
  cat >"$launcher" <<EOF
#!/usr/bin/env bash
# Generated by scripts/muse-key.sh. Starts Muse with its minted API key so it
# never needs the Keychain.
if [[ -z "\${META_API_KEY:-}" && -r "$key_file" ]]; then
  META_API_KEY="\$(<"$key_file")"
  export META_API_KEY
fi
exec "$real_muse" "\$@"
EOF
  chmod 755 "$launcher"
  # launchd cannot read scripts under ~/Downloads or ~/Documents (TCC), so run a copy.
  local self
  self="$(dirname "$launcher")/muse-key.sh"
  cp "$0" "$self"
  chmod 755 "$self"
  cat >"$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$label</string>
  <key>ProgramArguments</key><array><string>/bin/bash</string><string>$self</string><string>tick</string></array>
  <key>StartInterval</key><integer>900</integer>
  <key>RunAtLoad</key><true/>
  <key>StandardErrorPath</key><string>$dir/muse-key.log</string>
  <key>EnvironmentVariables</key><dict><key>PATH</key><string>$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string></dict>
</dict>
</plist>
EOF
  launchctl bootout "gui/$(id -u)/$label" >/dev/null 2>&1 || true
  launchctl bootstrap "gui/$(id -u)" "$plist"
  sync_key
  echo "launcher: $launcher"
  echo "set the Muse profile command to: $launcher exec --json"
}

uninstall() {
  launchctl bootout "gui/$(id -u)/$label" >/dev/null 2>&1 || true
  rm -f "$plist" "$launcher" "$(dirname "$launcher")/muse-key.sh" "$key_file" "$probe_stamp"
}

case "${1:-}" in
  install) install ;;
  sync) sync_key ;;
  check) check ;;
  tick) tick ;;
  uninstall) uninstall ;;
  *) sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'; exit 2 ;;
esac
